# Generated by Django 5.2.8 on 2025-11-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("konten", models.TextField()),
                ("tanggal_mulai", models.DateField()),
                ("tanggal_selesai", models.DateField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=True)),
                ("dibuat_pada", models.DateTimeField(auto_now_add=True)),
                ("diupdate_pada", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pengumuman",
                "verbose_name_plural": "Pengumuman",
                "ordering": ["-tanggal_mulai", "-dibuat_pada"],
            },
        ),
        migrations.CreateModel(
            name="FrequentlyAskedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pertanyaan", models.CharField(max_length=255)),
                ("jawaban", models.TextField()),
                ("urutan", models.PositiveIntegerField(default=1)),
                ("aktif", models.BooleanField(default=True)),
                ("dibuat_pada", models.DateTimeField(auto_now_add=True)),
                ("diupdate_pada", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
                "ordering": ["urutan", "-dibuat_pada"],
            },
        ),
    ]
