# Generated by Django 5.2.8 on 2025-11-21 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField(blank=True, null=True)),
                ('jam_selesai', models.TimeField(blank=True, null=True)),
                ('aktivitas', models.TextField(help_text='Deskripsikan kegiatan utama yang dilakukan pada hari tersebut.')),
                ('tools_yang_digunakan', models.CharField(blank=True, help_text='Contoh: Python, SQL, Power BI, Excel, dsb.', max_length=200, null=True)),
                ('output', models.TextField(blank=True, help_text='Hasil kerja: laporan, dashboard, script, dsb.', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft oleh mahasiswa'), ('SUBMIT', 'Diajukan ke dosen'), ('REVIEWED', 'Sudah ditinjau dosen')], default='DRAFT', max_length=10)),
                ('catatan_dosen', models.TextField(blank=True, help_text='Komentar/feedback dosen pembimbing terhadap aktivitas hari ini.', null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('dosen_pembimbing', models.ForeignKey(blank=True, help_text='Biasanya otomatis mengikuti dosen pembimbing mahasiswa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logbook_bimbingan', to='masterdata.dosen')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_entries', to='masterdata.mahasiswa')),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logbook_entries', to='masterdata.periodepkl')),
            ],
            options={
                'verbose_name': 'Entri Logbook',
                'verbose_name_plural': 'Entri Logbook',
                'ordering': ['-tanggal', '-dibuat_pada'],
            },
        ),
    ]
