# Generated by Django 5.2.8 on 2025-11-24 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
        ('masterdata', '0004_pendaftaranpkl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logbookentry',
            options={'verbose_name': 'Logbook', 'verbose_name_plural': 'Logbook'},
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='aktivitas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='catatan_dosen',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='dosen_pembimbing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logbook_entries', to='masterdata.dosen'),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='output',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (belum dikirim ke dosen)'), ('SUBMIT', 'Diajukan ke dosen'), ('REVISI', 'Perlu revisi'), ('DISETUJUI', 'Disetujui dosen')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='tools_yang_digunakan',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
