# Generated by Django 5.2.8 on 2025-11-21 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(max_length=20, unique=True, verbose_name='NIDN')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True, verbose_name='No. HP/WA')),
                ('prodi', models.CharField(default='Sains Data', help_text='Misalnya: Sains Data, Sistem Informasi, Informatika', max_length=100)),
                ('kuota_bimbingan', models.PositiveIntegerField(default=10, help_text='Maksimal jumlah mahasiswa PKL yang dibimbing pada satu periode.')),
            ],
            options={
                'verbose_name': 'Dosen',
                'verbose_name_plural': 'Dosen',
            },
        ),
        migrations.CreateModel(
            name='Mitra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('kota', models.CharField(blank=True, max_length=100, null=True)),
                ('pic_nama', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama PIC')),
                ('pic_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email PIC')),
                ('pic_no_hp', models.CharField(blank=True, max_length=20, null=True, verbose_name='No. HP PIC')),
                ('bidang_usaha', models.CharField(blank=True, help_text='Contoh: Konsultan Data, Perbankan, Pemerintahan, dsb.', max_length=200, null=True)),
                ('kuota_pkl', models.PositiveIntegerField(default=5, help_text='Perkiraan maksimal mahasiswa PKL yang dapat diterima per periode.')),
            ],
            options={
                'verbose_name': 'Mitra',
                'verbose_name_plural': 'Mitra',
            },
        ),
        migrations.CreateModel(
            name='PeriodePKL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_periode', models.CharField(help_text='Misal: PKL 2025 Gasal', max_length=100)),
                ('tahun_ajaran', models.CharField(help_text='Misal: 2025/2026', max_length=20)),
                ('semester', models.CharField(choices=[('GASAL', 'Gasal'), ('GENAP', 'Genap'), ('PENDEK', 'Antara/Pendek')], max_length=10)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('aktif', models.BooleanField(default=True, help_text='Centang jika periode ini sedang berjalan.')),
            ],
            options={
                'verbose_name': 'Periode PKL',
                'verbose_name_plural': 'Periode PKL',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True, verbose_name='No. HP/WA')),
                ('angkatan', models.PositiveIntegerField(help_text='Tahun angkatan, misal: 2022')),
                ('prodi', models.CharField(default='Sains Data', help_text='Untuk sekarang bisa diisi default Sains Data.', max_length=100)),
                ('status_pkl', models.CharField(choices=[('BELUM', 'Belum PKL'), ('SEDANG', 'Sedang PKL'), ('SELESAI', 'Selesai PKL')], default='BELUM', max_length=10)),
                ('dosen_pembimbing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahasiswa_bimbingan', to='masterdata.dosen')),
                ('mitra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahasiswa_pkl', to='masterdata.mitra')),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahasiswa_pkl', to='masterdata.periodepkl')),
            ],
            options={
                'verbose_name': 'Mahasiswa',
                'verbose_name_plural': 'Mahasiswa',
            },
        ),
    ]
