# Generated by Django 5.2.8 on 2025-11-21 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User akun untuk login sebagai dosen.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dosen_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
