# Generated by Django 5.2.8 on 2025-11-22 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_dosen_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User akun untuk login mahasiswa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
