# Generated by Django 5.2.8 on 2025-11-22 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_mahasiswa_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendaftaranPKL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_pkl', models.CharField(choices=[('INDIVIDU', 'Individu'), ('KELOMPOK', 'Kelompok')], max_length=10)),
                ('anggota_kelompok', models.TextField(blank=True, help_text='Jika PKL kelompok, tuliskan NIM dan nama anggota lain.')),
                ('surat_penerimaan', models.FileField(help_text='Upload surat penerimaan dari perusahaan (PDF/JPG).', upload_to='surat_penerimaan/')),
                ('status', models.CharField(choices=[('DIKIRIM', 'Diajukan'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak')], default='DIKIRIM', max_length=10)),
                ('catatan_koordinator', models.TextField(blank=True, help_text='Catatan/pertimbangan koordinator PKL.')),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('dosen_pembimbing', models.ForeignKey(blank=True, help_text='Diisi oleh koordinator PKL setelah pendaftaran disetujui.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendaftaran_pkl', to='masterdata.dosen')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran_pkl', to='masterdata.mahasiswa')),
                ('mitra', models.ForeignKey(help_text='Perusahaan/mitra tempat PKL', on_delete=django.db.models.deletion.PROTECT, related_name='pendaftaran_pkl', to='masterdata.mitra')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendaftaran_pkl', to='masterdata.periodepkl')),
            ],
            options={
                'verbose_name': 'Pendaftaran PKL',
                'verbose_name_plural': 'Pendaftaran PKL',
                'unique_together': {('mahasiswa', 'periode')},
            },
        ),
    ]
