# Generated by Django 5.2.8 on 2025-11-24 03:20

import masterdata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_pendaftaranpkl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaranpkl',
            name='surat_penerimaan',
            field=models.FileField(help_text='Upload surat penerimaan (PDF/JPG/PNG, maks. 2 MB).', upload_to='surat_penerimaan/', validators=[masterdata.models.validate_surat_penerimaan_file]),
        ),
    ]
