# Generated by Django 5.2.8 on 2025-11-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_alter_pendaftaranpkl_surat_penerimaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='is_koordinator_pkl',
            field=models.BooleanField(default=False, help_text='Centang jika dosen ini bertindak sebagai koordinator PKL.'),
        ),
    ]
