# Generated by Django 5.2.8 on 2025-11-24 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_dosen_is_koordinator_pkl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarHasilPKL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_laporan', models.CharField(max_length=255)),
                ('file_laporan', models.FileField(help_text='Upload laporan PKL (PDF).', upload_to='laporan_pkl/')),
                ('status', models.CharField(choices=[('DIKIRIM', 'Diajukan'), ('DIJADWALKAN', 'Dijadwalkan'), ('SELESAI', 'Selesai'), ('DITOLAK', 'Ditolak')], default='DIKIRIM', max_length=15)),
                ('jadwal', models.DateTimeField(blank=True, help_text='Tanggal & jam seminar hasil PKL.', null=True)),
                ('ruang', models.CharField(blank=True, help_text='Ruang ujian / link meeting.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosen_pembimbing', models.ForeignKey(blank=True, help_text='Biasanya otomatis mengikuti dosen pembimbing PKL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminar_pkl_dibimbing', to='masterdata.dosen')),
                ('dosen_penguji_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminar_pkl_diuji_1', to='masterdata.dosen')),
                ('dosen_penguji_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminar_pkl_diuji_2', to='masterdata.dosen')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_pkl', to='masterdata.mahasiswa')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seminar_pkl', to='masterdata.periodepkl')),
            ],
            options={
                'verbose_name': 'Seminar Hasil PKL',
                'verbose_name_plural': 'Seminar Hasil PKL',
                'unique_together': {('mahasiswa', 'periode')},
            },
        ),
    ]
