# Generated by Django 5.2.8 on 2025-11-26 07:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_seminarhasilpkl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemahaman_materi', models.PositiveSmallIntegerField(help_text='Pemahaman materi, latar belakang, dan tujuan PKL', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kualitas_laporan', models.PositiveSmallIntegerField(help_text='Kerapian & kelengkapan laporan PKL', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('presentasi', models.PositiveSmallIntegerField(help_text='Kemampuan presentasi & komunikasi', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('penguasaan_lapangan', models.PositiveSmallIntegerField(help_text='Penguasaan hasil, data, dan proses kerja di lapangan', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sikap_profesional', models.PositiveSmallIntegerField(help_text='Sikap, etika, dan kedisiplinan selama seminar', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nilai_angka', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('nilai_huruf', models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('E', 'E')], editable=False, max_length=2)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('penguji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_assessments', to='masterdata.dosen')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='masterdata.seminarhasilpkl')),
            ],
            options={
                'verbose_name': 'Penilaian Seminar PKL',
                'verbose_name_plural': 'Penilaian Seminar PKL',
                'unique_together': {('seminar', 'penguji')},
            },
        ),
    ]
