# Generated by Django 5.2.8 on 2025-12-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0009_seminarassessment_role_rename_penguji'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaranpkl',
            name='tanggal_mulai_pkl',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaranpkl',
            name='tanggal_selesai_pkl',
            field=models.DateField(blank=True, null=True),
        ),
    ]
