# Generated by Django 5.2.8 on 2025-12-18 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_pendaftaranpkl_tanggal_mulai_pkl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaranpkl',
            name='mitra',
            field=models.ForeignKey(help_text='Perusahaan/mitra tempat PKL', on_delete=django.db.models.deletion.PROTECT, related_name='pendaftaran_pkl_list', to='masterdata.mitra'),
        ),
    ]
