# Generated by Django 5.2.8 on 2025-12-24 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0011_alter_pendaftaranpkl_mitra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosen',
            options={},
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='is_koordinator_pkl',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='kuota_bimbingan',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='prodi',
        ),
        migrations.AddField(
            model_name='dosen',
            name='nip',
            field=models.CharField(blank=True, help_text='Opsional (misalnya untuk dosen ASN).', max_length=50, null=True, unique=True, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nama',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nidn',
            field=models.CharField(help_text='Isi dengan NIDN atau NUPTK (pilih salah satu).', max_length=50, unique=True, verbose_name='NIDN/NUPTK'),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='no_hp',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosen_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
