# Generated by Django 5.2.8 on 2025-11-21 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertemuan_ke', models.PositiveIntegerField(blank=True, help_text='Nomor pertemuan, misalnya 1, 2, 3, ...', null=True)),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField(blank=True, null=True)),
                ('jam_selesai', models.TimeField(blank=True, null=True)),
                ('metode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('HYBRID', 'Hybrid')], default='ONLINE', max_length=10)),
                ('platform', models.CharField(blank=True, help_text='Misalnya: Zoom, GMeet, WhatsApp Call, Ruang Dosen 3.4, dsb.', max_length=100, null=True)),
                ('topik', models.CharField(help_text='Judul/topik utama bimbingan. Misal: Review proposal, revisi laporan, dsb.', max_length=200)),
                ('ringkasan_diskusi', models.TextField(help_text='Ringkasan poin-poin yang dibahas dalam bimbingan.')),
                ('tindak_lanjut', models.TextField(blank=True, help_text='Action item/tugas yang harus dikerjakan mahasiswa setelah bimbingan.', null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Terjadwal'), ('DONE', 'Selesai'), ('CANCELLED', 'Dibatalkan')], default='PLANNED', max_length=10)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('dosen_pembimbing', models.ForeignKey(blank=True, help_text='Biasanya otomatis mengikuti dosen pembimbing mahasiswa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidance_sessions', to='masterdata.dosen')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_sessions', to='masterdata.mahasiswa')),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidance_sessions', to='masterdata.periodepkl')),
            ],
            options={
                'verbose_name': 'Sesi Bimbingan',
                'verbose_name_plural': 'Sesi Bimbingan',
                'ordering': ['-tanggal', '-dibuat_pada'],
            },
        ),
    ]
